save_data: /opt/ml/input/data/training/en-ja/jparacrawl
## Where the vocab(s) will be written
src_vocab: /opt/ml/input/data/training/en-ja/jparacrawl.vocab.src
tgt_vocab: /opt/ml/input/data/training/en-ja/jparacrawl.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: /opt/ml/input/data/training/en-ja/train.en
        path_tgt: /opt/ml/input/data/training/en-ja/train.ja
    valid:
        path_src: /opt/ml/input/data/training/en-ja/val.en
        path_tgt: /opt/ml/input/data/training/en-ja/val.ja

#data: /opt/ml/model/dataset.en_ja
save_model: /opt/ml/model/model.en-ja
save_checkpoint_steps: 10000
keep_checkpoint: 10
seed: 3435
train_steps: 40000
valid_steps: 10000
warmup_steps: 8000
report_every: 100

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 2
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 4
gpu_ranks:
- 0
- 1
- 2
- 3